const types = {
    FETCH_CRYPTO_NEWS_REQUEST: "FETCH_CRYPTO_NEWS_REQUEST",
    FETCH_CRYPTO_NEWS_SUCCESS: "FETCH_CRYPTO_NEWS_SUCCESS",
    FETCH_CRYPTO_NEWS_FAILED: "FETCH_CRYPTO_NEWS_FAILED",
    FETCH_CRYPTO_NEWS_SEARCH: "FETCH_CRYPTO_NEWS_SEARCH",
};


export default types
