const types = {
    FETCH_CRYPTO_COINS_REQUEST: "FETCH_CRYPTO_COINS_REQUEST",
    FETCH_CRYPTO_COINS_SUCCESS: "FETCH_CRYPTO_COINS_SUCCESS",
    FETCH_CRYPTO_COINS_FAILED: "FETCH_CRYPTO_COINS_FAILED",
    FETCH_CRYPTO_COINS_SEARCH: "FETCH_CRYPTO_COINS_SEARCH",
};


export default types
